# Generated by Django 3.2.5 on 2021-11-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_mypost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
