# Generated by Django 3.2.5 on 2021-11-11 06:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_alter_mypost_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyPost',
            new_name='Post',
        ),
    ]
