# Generated by Django 3.2.5 on 2021-10-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=164)),
                ('l_name', models.CharField(max_length=164)),
                ('email', models.EmailField(max_length=164, unique=True)),
            ],
        ),
    ]
